#!/bin/bash
# ===============================================
# 推送本地图片到GitHub PIC库
# 功能: 将本地生成的图片推送到Alexxiang2008/PIC仓库
# 作者: Alex - AI Skills System
# 更新: 2025年12月13日
# ===============================================

set -e

# 配置
LOCAL_PIC_DIR="$(dirname "$0")"
TARGET_DIR="7个AI工具解决外贸获客成本痛点"
GITHUB_REPO="Alexxiang2008/PIC"
GITHUB_TOKEN="YOUR_GITHUB_TOKEN_HERE"  # 需要替换为实际的token

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

echo_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

echo_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 检查目标目录是否存在
if [ ! -d "$LOCAL_PIC_DIR/$TARGET_DIR" ]; then
    echo_error "目标目录不存在: $TARGET_DIR"
    exit 1
fi

echo_info "开始推送图片到GitHub PIC库..."
echo_info "本地目录: $LOCAL_PIC_DIR/$TARGET_DIR"
echo_info "目标仓库: $GITHUB_REPO"

# 检查是否有Git仓库
if [ ! -d "$LOCAL_PIC_DIR/.git" ]; then
    echo_info "初始化Git仓库..."
    cd "$LOCAL_PIC_DIR"
    git init
    git remote add origin "https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git"
    git branch -M main
else
    cd "$LOCAL_PIC_DIR"
    # 检查远程仓库是否配置正确
    if ! git remote get-url origin | grep -q "$GITHUB_REPO"; then
        echo_info "更新远程仓库地址..."
        git remote set-url origin "https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git"
    fi
fi

# 检查token是否已配置
if echo "$GITHUB_TOKEN" | grep -q "YOUR_GITHUB_TOKEN_HERE"; then
    echo_error "请先配置GitHub Token！"
    echo_info "编辑此脚本，将 YOUR_GITHUB_TOKEN_HERE 替换为实际的GitHub Personal Access Token"
    exit 1
fi

# 添加文件
echo_info "添加图片文件到Git..."
git add "$TARGET_DIR/"

# 检查是否有更改
if git diff --cached --quiet; then
    echo_warn "没有文件需要提交"
    exit 0
fi

# 提交更改
echo_info "提交更改..."
git commit -m "Add images for article: 7个AI工具解决外贸获客成本痛点

Generated by AI Writing System v4.0
Date: $(date '+%Y-%m-%d %H:%M:%S')
Images included:
- 获客成本对比图表.html
- AI内容生成自动化流程.html
- AI客户分析仪表盘.html
- AI获客管理系统界面.html
- ROI计算图表.html
- 封面图.html"

# 推送到GitHub
echo_info "推送到GitHub..."
git push origin main

echo_info "推送完成！"
echo_info "图片已推送到: https://github.com/$GITHUB_REPO/tree/main/$TARGET_DIR"
echo_info "可以通过以下链接访问图片："
echo_info "https://raw.githubusercontent.com/$GITHUB_REPO/main/$TARGET_DIR/[文件名]"

echo_info "推送成功完成！"